### ISSUE TITLE
Add an option to disable "Fixed Shotgun Damage".

### ISSUE THREAD

**Issue by AJAL8000** [1A3Dev/LC-LethalFixes#1]
I find it a huge disadvantage that others are able to kill a Forest Keeper with a shot or two without mods, while one with this mod cannot. Especially considering how buggy and ugly these enemies are to deal with.

**Comment by 1A3Dev** [comment]
I made Zeekers aware of the issue a day or two before I added the fix to this mod so it's probably fixed for the next base game update already therefore there's not really any reason why you should be able to disable this fix?

**Comment by AJAL8000** [comment]
Well, but maybe you could add the option in the meantime, while Zeekers releases version v51.

If the v51 update does not come out for 1 or 2 months, I see that it is still a time where it would be worth adding the option and then removing it when it is already in the game.

But well now that I know that you informed Zeekers about the error, I suppose I don't have much problem waiting, but for my part I would still like you to add the option, if it isn't too much trouble.
