### ISSUE TITLE
[Enhancement] Add an option to disable PTT indicator & NoPropShadows

### ISSUE THREAD

**Issue by zndrmn** [1A3Dev/LC-LethalFixes#2]
Add an option to disable PTT indicator & NoPropShadows

Also I'm not sure if this is within the scope of this mod but would it be possible to have a way to have a toggle mute button for open mic users?
And when it's disabled it'll show the PTT indicator but crossed out or slightly red in the top left where it normally goes
If that does get added it would be nice if the PTT indicator when muted always shows no matter if the PTT indicator is disabled or not (or maybe just have a setting for that as well)

**Comment by 1A3Dev** [comment]
If you mean disabling the PTT indicator specifically for voice activation then that's already planned and was requested by someone a few hours ago.

I'm confused why you would want to disable the NoPropShadows though? Since it doesn't change much graphics wise and results in better performance

**Comment by zndrmn** [comment]
> If you mean disabling the PTT indicator specifically for voice activation then that's already planned and was requested by someone a few hours ago.

Yeah that's what I meant

> I'm confused why you would want to disable the NoPropShadows though? Since it doesn't change much graphics wise and results in better performance

I just like how the ship looks when there's a bunch of light props.
It just would be nice for picky people like me lol.
And I'm also not too worried about the performance on the ship when there's a ton of light props.
idk I'm weird

**Comment by 1A3Dev** [comment]
The option to disable the PTT indicator for voice activation has been added in [v1.1.1](https://github.com/1A3Dev/LC-LethalFixes/releases/tag/v1.1.1)
