### ISSUE TITLE
[Fix] Stormy weather

### ISSUE THREAD

**Issue by ZigzagAwaka** [1A3Dev/LC-LethalFixes#7]
I don't know if it's real or not, but stormy weather does not seem to work anymore on v64 (not targeting metalic tools and scraps)
Can you fix that ?

**Comment by 1A3Dev** [comment]
You can use https://thunderstore.io/c/lethal-company/p/ButteryStancakes/ButteryFixes/ to fix that, it should be fully compatible with this mod.

**Comment by ZigzagAwaka** [comment]
Yeah i already knew that, but I don't need 95% of the fixes in this mod + installing thousands of pack fix mods is not a general good idea
I feel like LethalFixes is the best go-to vanilla fix mod for Lethal Company, so the best would be for you to add this fix aswell

**Comment by 1A3Dev** [comment]
> I don't need 95% of the fixes in that mod

Well it's always good to have fixes for vanilla issues even if you might not think you necessarily need them

> installing thousands of pack fix mods is not a general good idea

It's not a bad idea, more mods doesn't mean worse performance compared to a bunch of fixes in a single mod. I personally only use bug fix and quality of life mods which are all vanilla compatible and I have around 60 mods total

> so the best would be for you to add this fix aswell

There isn't really any point in me stealing fixes from another mod when you can just use both mods together.

**Comment by ZigzagAwaka** [comment]
I understand you completly, and again I didn't said that you should steal the code
LethalFixes is just my personnal favorite and even if it's compatible with other mods there is still a manual config process that you have to make in order to have full compatiblity
For example, both ButteryFixes and GeneralImprovements are fixing the fire exit rotation so without disabling one of them the player will do a full 360 degrees rotation
That's just an example of course

**Comment by ZigzagAwaka** [comment]
But of course if you really don't want to add it, that's fair and i respect your choice

**Comment by ZigzagAwaka** [comment]
Fixed in vanilla in the latest LC update
